// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250719154324_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.BhtForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalConcern")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BehaviorData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BehaviorSubject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BehaviorTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FBA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MainConcern")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ParentNotified")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<string>("StudentInitial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StudentStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StudentStrength")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TeacherEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TierOne")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TierThree")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TierTwo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BhtForms");
                });

            modelBuilder.Entity("backend.Models.DrForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("HomeroomTeacher")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MajorProblemBehavior")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MinorProblemBehavior")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Narrative")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NextSteps")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProactiveConcern")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SELCompetency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StudentFirst")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StudentLast")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TeacherIntervention")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DrForms");
                });
#pragma warning restore 612, 618
        }
    }
}
